/**
 * cities.ts
 * Municipios colombianos de expedición más frecuentes, con su grafía oficial.
 * Se usa para restaurar tildes y detectar cuando el auditor escribió
 * departamento o país dentro de `lugarexpedicion`.
 */

/** Forma exacta exigida por la institución para la capital. */
export const BOGOTA_CANONICAL = 'Bogotá D.C.';

/**
 * Variantes normalizadas que deben convertirse en `Bogotá D.C.`.
 * Las claves se comparan sin tildes, en minúscula y sin puntuación.
 */
export const BOGOTA_VARIANTS = new Set<string>([
  'bogota',
  'bogota dc',
  'bogota d c',
  'bogota distrito capital',
  'bogota cundinamarca',
  'bogota colombia',
  'santafe de bogota',
  'santa fe de bogota',
  'bogota d c colombia',
  'bta',
]);

/**
 * Municipios con su grafía oficial. La clave es la forma normalizada
 * (minúscula, sin tildes, sin puntuación, espacios colapsados).
 */
export const CITY_CANONICAL: Record<string, string> = {
  medellin: 'Medellín',
  cali: 'Cali',
  'santiago de cali': 'Cali',
  barranquilla: 'Barranquilla',
  cartagena: 'Cartagena',
  'cartagena de indias': 'Cartagena',
  cucuta: 'Cúcuta',
  'san jose de cucuta': 'Cúcuta',
  bucaramanga: 'Bucaramanga',
  pereira: 'Pereira',
  'santa marta': 'Santa Marta',
  ibague: 'Ibagué',
  pasto: 'Pasto',
  'san juan de pasto': 'Pasto',
  manizales: 'Manizales',
  neiva: 'Neiva',
  villavicencio: 'Villavicencio',
  armenia: 'Armenia',
  valledupar: 'Valledupar',
  monteria: 'Montería',
  sincelejo: 'Sincelejo',
  popayan: 'Popayán',
  buenaventura: 'Buenaventura',
  palmira: 'Palmira',
  riohacha: 'Riohacha',
  tunja: 'Tunja',
  florencia: 'Florencia',
  quibdo: 'Quibdó',
  yopal: 'Yopal',
  mocoa: 'Mocoa',
  arauca: 'Arauca',
  leticia: 'Leticia',
  'puerto carreno': 'Puerto Carreño',
  inirida: 'Inírida',
  'san jose del guaviare': 'San José del Guaviare',
  mitu: 'Mitú',
  'san andres': 'San Andrés',
  soacha: 'Soacha',
  bello: 'Bello',
  itagui: 'Itagüí',
  envigado: 'Envigado',
  rionegro: 'Rionegro',
  sabaneta: 'Sabaneta',
  caldas: 'Caldas',
  copacabana: 'Copacabana',
  apartado: 'Apartadó',
  turbo: 'Turbo',
  soledad: 'Soledad',
  malambo: 'Malambo',
  sogamoso: 'Sogamoso',
  duitama: 'Duitama',
  chiquinquira: 'Chiquinquirá',
  zipaquira: 'Zipaquirá',
  facatativa: 'Facatativá',
  chia: 'Chía',
  fusagasuga: 'Fusagasugá',
  girardot: 'Girardot',
  mosquera: 'Mosquera',
  madrid: 'Madrid',
  funza: 'Funza',
  cajica: 'Cajicá',
  ubate: 'Ubaté',
  'villa de leyva': 'Villa de Leyva',
  tulua: 'Tuluá',
  cartago: 'Cartago',
  buga: 'Buga',
  'guadalajara de buga': 'Buga',
  jamundi: 'Jamundí',
  yumbo: 'Yumbo',
  candelaria: 'Candelaria',
  florida: 'Florida',
  zarzal: 'Zarzal',
  roldanillo: 'Roldanillo',
  'la union': 'La Unión',
  sevilla: 'Sevilla',
  caicedonia: 'Caicedonia',
  espinal: 'Espinal',
  melgar: 'Melgar',
  honda: 'Honda',
  chaparral: 'Chaparral',
  libano: 'Líbano',
  girardota: 'Girardota',
  barrancabermeja: 'Barrancabermeja',
  'floridablanca': 'Floridablanca',
  giron: 'Girón',
  piedecuesta: 'Piedecuesta',
  'san gil': 'San Gil',
  socorro: 'Socorro',
  malaga: 'Málaga',
  ocana: 'Ocaña',
  pamplona: 'Pamplona',
  'villa del rosario': 'Villa del Rosario',
  'los patios': 'Los Patios',
  tumaco: 'Tumaco',
  ipiales: 'Ipiales',
  tuquerres: 'Túquerres',
  'la union narino': 'La Unión',
  'santander de quilichao': 'Santander de Quilichao',
  puerto: 'Puerto',
  garzon: 'Garzón',
  pitalito: 'Pitalito',
  'la plata': 'La Plata',
  campoalegre: 'Campoalegre',
  aguachica: 'Aguachica',
  'agustin codazzi': 'Agustín Codazzi',
  'el banco': 'El Banco',
  cienaga: 'Ciénaga',
  fundacion: 'Fundación',
  plato: 'Plato',
  'magangue': 'Magangué',
  turbaco: 'Turbaco',
  arjona: 'Arjona',
  'el carmen de bolivar': 'El Carmen de Bolívar',
  corozal: 'Corozal',
  sahagun: 'Sahagún',
  cerete: 'Cereté',
  lorica: 'Lorica',
  planeta: 'Planeta Rica',
  'planeta rica': 'Planeta Rica',
  montelibano: 'Montelíbano',
  maicao: 'Maicao',
  uribia: 'Uribia',
  'san juan del cesar': 'San Juan del Cesar',
  'dosquebradas': 'Dosquebradas',
  'santa rosa de cabal': 'Santa Rosa de Cabal',
  'la dorada': 'La Dorada',
  chinchina: 'Chinchiná',
  riosucio: 'Riosucio',
  'villamaria': 'Villamaría',
  calarca: 'Calarcá',
  montenegro: 'Montenegro',
  'la tebaida': 'La Tebaida',
  circasia: 'Circasia',
  quimbaya: 'Quimbaya',
  acacias: 'Acacías',
  granada: 'Granada',
  'puerto lopez': 'Puerto López',
  'puerto asis': 'Puerto Asís',
  sibundoy: 'Sibundoy',
  'aguazul': 'Aguazul',
  'villanueva': 'Villanueva',
  saravena: 'Saravena',
  'tame': 'Tame',
  moniquira: 'Moniquirá',
  mexico: 'México',
  'la mesa': 'La Mesa',
  'la calera': 'La Calera',
  sopo: 'Sopó',
  tocancipa: 'Tocancipá',
  guaduas: 'Guaduas',
  subachoque: 'Subachoque',


  /*
   * A partir de aquí: catálogo completo de los municipios de Colombia
   * (los 32 departamentos), tomado del Registro Único de Entidades
   * Territoriales. Cubre también los pueblos pequeños donde se expiden
   * cédulas y que antes no estaban: Restrepo, Rivera, Paipa, Cotorra, etc.
   * Las entradas de arriba (alias y grafías ya verificadas contra el uso
   * real de la institución) tienen prioridad: ninguna clave se repite.
   */
  "abejorral": "Abejorral",
  "abrego": "Ábrego",
  "abriaqui": "Abriaquí",
  "acandi": "Acandí",
  "acevedo": "Acevedo",
  "achi": "Achí",
  "agrado": "Agrado",
  "agua de dios": "Agua de Dios",
  "aguada": "Aguada",
  "aguadas": "Aguadas",
  "aipe": "Aipe",
  "alban": "Albán",
  "albania": "Albania",
  "alcala": "Alcalá",
  "aldana": "Aldana",
  "alejandria": "Alejandría",
  "algarrobo": "Algarrobo",
  "algeciras": "Algeciras",
  "almaguer": "Almaguer",
  "almeida": "Almeida",
  "alpujarra": "Alpujarra",
  "altamira": "Altamira",
  "alto baudo": "Alto Baudó",
  "altos del rosario": "Altos del Rosario",
  "alvarado": "Alvarado",
  "amaga": "Amagá",
  "amalfi": "Amalfi",
  "ambalema": "Ambalema",
  "anapoima": "Anapoima",
  "ancuya": "Ancuyá",
  "andalucia": "Andalucía",
  "andes": "Andes",
  "angelopolis": "Angelópolis",
  "angostura": "Angostura",
  "anolaima": "Anolaima",
  "anori": "Anorí",
  "anserma": "Anserma",
  "ansermanuevo": "Ansermanuevo",
  "anza": "Anzá",
  "anzoategui": "Anzoátegui",
  "apia": "Apía",
  "apulo": "Apulo",
  "aquitania": "Aquitania",
  "aracataca": "Aracataca",
  "aranzazu": "Aranzazu",
  "aratoca": "Aratoca",
  "arauquita": "Arauquita",
  "arbelaez": "Arbeláez",
  "arboleda": "Arboleda",
  "arboledas": "Arboledas",
  "arboletes": "Arboletes",
  "arcabuco": "Arcabuco",
  "arenal": "Arenal",
  "argelia": "Argelia",
  "ariguani": "Ariguaní",
  "armero": "Armero",
  "arroyohondo": "Arroyohondo",
  "astrea": "Astrea",
  "ataco": "Ataco",
  "ayapel": "Ayapel",
  "bagado": "Bagadó",
  "bahia solano": "Bahía Solano",
  "bajo baudo": "Bajo Baudó",
  "balboa": "Balboa",
  "baranoa": "Baranoa",
  "baraya": "Baraya",
  "barbacoas": "Barbacoas",
  "barbosa": "Barbosa",
  "barichara": "Barichara",
  "barranca de upia": "Barranca de Upía",
  "barrancas": "Barrancas",
  "barranco de loba": "Barranco de Loba",
  "becerril": "Becerril",
  "belalcazar": "Belalcázar",
  "belen": "Belén",
  "belen de los andaquies": "Belén de los Andaquíes",
  "belen de umbria": "Belén de Umbría",
  "belmira": "Belmira",
  "beltran": "Beltrán",
  "berbeo": "Berbeo",
  "betania": "Betania",
  "beteitiva": "Betéitiva",
  "betulia": "Betulia",
  "bituima": "Bituima",
  "boavita": "Boavita",
  "bochalema": "Bochalema",
  "bojaca": "Bojacá",
  "bojaya": "Bojayá",
  "bolivar": "Bolívar",
  "bosconia": "Bosconia",
  "boyaca": "Boyacá",
  "brazuelo de papayal": "Brazuelo de Papayal",
  "briceno": "Briceño",
  "bucarasica": "Bucarasica",
  "buenavista": "Buenavista",
  "buenos aires": "Buenos Aires",
  "buesaco": "Buesaco",
  "bugalagrande": "Bugalagrande",
  "buritica": "Buriticá",
  "busbanza": "Busbanzá",
  "cabrera": "Cabrera",
  "cabuyaro": "Cabuyaro",
  "caceres": "Cáceres",
  "cachipay": "Cachipay",
  "cachira": "Cáchira",
  "cacota": "Cácota",
  "caicedo": "Caicedo",
  "caimito": "Caimito",
  "cajamarca": "Cajamarca",
  "cajibio": "Cajibío",
  "calamar": "Calamar",
  "caldono": "Caldono",
  "california": "California",
  "calima": "Calima",
  "caloto": "Caloto",
  "campamento": "Campamento",
  "campo de la cruz": "Campo de la Cruz",
  "campohermoso": "Campohermoso",
  "canalete": "Canalete",
  "canasgordas": "Cañasgordas",
  "cantagallo": "Cantagallo",
  "canton de san pablo": "Cantón de San Pablo",
  "caparrapi": "Caparrapí",
  "capitanejo": "Capitanejo",
  "caqueza": "Cáqueza",
  "caracoli": "Caracolí",
  "caramanta": "Caramanta",
  "carcasi": "Carcasí",
  "carepa": "Carepa",
  "carmen de apicala": "Carmen de Apicalá",
  "carmen de carupa": "Carmen de Carupa",
  "carolina del principe": "Carolina del Príncipe",
  "cartagena del chaira": "Cartagena del Chairá",
  "caruru": "Carurú",
  "casabianca": "Casabianca",
  "castilla la nueva": "Castilla la Nueva",
  "caucasia": "Caucasia",
  "cepita": "Cepitá",
  "cerinza": "Cerinza",
  "cerrito": "Cerrito",
  "cerro de san antonio": "Cerro de San Antonio",
  "certegui": "Certegui",
  "chachagui": "Chachagüí",
  "chaguani": "Chaguaní",
  "chalan": "Chalán",
  "chameza": "Chámeza",
  "charala": "Charalá",
  "charta": "Charta",
  "chibolo": "Chibolo",
  "chigorodo": "Chigorodó",
  "chima": "Chimá",
  "chimichagua": "Chimichagua",
  "chinacota": "Chinácota",
  "chinavita": "Chinavita",
  "chinu": "Chinú",
  "chipaque": "Chipaque",
  "chipata": "Chipatá",
  "chiquiza": "Chíquiza",
  "chiriguana": "Chiriguaná",
  "chiscas": "Chiscas",
  "chita": "Chita",
  "chitaga": "Chitagá",
  "chitaraque": "Chitaraque",
  "chivata": "Chivatá",
  "chivor": "Chivor",
  "choachi": "Choachí",
  "choconta": "Chocontá",
  "cicuco": "Cicuco",
  "cienaga de oro": "Ciénaga de Oro",
  "cienega": "Ciénega",
  "cimitarra": "Cimitarra",
  "cisneros": "Cisneros",
  "ciudad bolivar": "Ciudad Bolívar",
  "clemencia": "Clemencia",
  "cocorna": "Cocorná",
  "coello": "Coello",
  "cogua": "Cogua",
  "colombia": "Colombia",
  "colon": "Colón",
  "coloso": "Colosó",
  "combita": "Cómbita",
  "concepcion": "Concepción",
  "concordia": "Concordia",
  "condoto": "Condoto",
  "confines": "Confines",
  "consaca": "Consacá",
  "contadero": "Contadero",
  "contratacion": "Contratación",
  "convencion": "Convención",
  "coper": "Coper",
  "cordoba": "Córdoba",
  "corinto": "Corinto",
  "coromoro": "Coromoro",
  "corrales": "Corrales",
  "cota": "Cota",
  "cotorra": "Cotorra",
  "covarachia": "Covarachía",
  "covenas": "Coveñas",
  "coyaima": "Coyaima",
  "cravo norte": "Cravo Norte",
  "cuaspud": "Cuaspud",
  "cubara": "Cubará",
  "cubarral": "Cubarral",
  "cucaita": "Cucaita",
  "cucunuba": "Cucunubá",
  "cucutilla": "Cucutilla",
  "cuitiva": "Cuítiva",
  "cumaral": "Cumaral",
  "cumaribo": "Cumaribo",
  "cumbal": "Cumbal",
  "cumbitara": "Cumbitara",
  "cunday": "Cunday",
  "curillo": "Curillo",
  "curiti": "Curití",
  "curumani": "Curumaní",
  "dabeiba": "Dabeiba",
  "dagua": "Dagua",
  "dibulla": "Dibulla",
  "distraccion": "Distracción",
  "dolores": "Dolores",
  "donmatias": "Donmatías",
  "durania": "Duranía",
  "ebejico": "Ebéjico",
  "el aguila": "El Águila",
  "el atrato": "El Atrato",
  "el bagre": "El Bagre",
  "el cairo": "El Cairo",
  "el calvario": "El Calvario",
  "el carmen": "El Carmen",
  "el carmen de atrato": "El Carmen de Atrato",
  "el carmen de chucuri": "El Carmen de Chucurí",
  "el carmen de viboral": "El Carmen de Viboral",
  "el carmen del darien": "El Carmen del Darién",
  "el castillo": "El Castillo",
  "el cerrito": "El Cerrito",
  "el charco": "El Charco",
  "el cocuy": "El Cocuy",
  "el colegio": "El Colegio",
  "el copey": "El Copey",
  "el doncello": "El Doncello",
  "el dorado": "El Dorado",
  "el dovio": "El Dovio",
  "el espinal": "El Espinal",
  "el espino": "El Espino",
  "el guacamayo": "El Guacamayo",
  "el guamo": "El Guamo",
  "el molino": "El Molino",
  "el paso": "El Paso",
  "el paujil": "El Paujil",
  "el penol": "El Peñol",
  "el penon": "El Peñón",
  "el pinon": "El Piñón",
  "el pital": "El Pital",
  "el playon": "El Playón",
  "el reten": "El Retén",
  "el retiro": "El Retiro",
  "el retorno": "El Retorno",
  "el roble": "El Roble",
  "el rosal": "El Rosal",
  "el rosario": "El Rosario",
  "el santuario": "El Santuario",
  "el socorro": "El Socorro",
  "el tablon": "El Tablón",
  "el tambo": "El Tambo",
  "el tarra": "El Tarra",
  "el zulia": "El Zulia",
  "elias": "Elías",
  "encino": "Encino",
  "enciso": "Enciso",
  "entrerrios": "Entrerríos",
  "falan": "Falán",
  "filadelfia": "Filadelfia",
  "filandia": "Filandia",
  "firavitoba": "Firavitoba",
  "flandes": "Flandes",
  "floresta": "Floresta",
  "florian": "Florián",
  "fomeque": "Fómeque",
  "fonseca": "Fonseca",
  "fortul": "Fortul",
  "fosca": "Fosca",
  "francisco pizarro": "Francisco Pizarro",
  "fredonia": "Fredonia",
  "fresno": "Fresno",
  "frontino": "Frontino",
  "fuente de oro": "Fuente de Oro",
  "funes": "Funes",
  "fuquene": "Fúquene",
  "gachala": "Gachalá",
  "gachancipa": "Gachancipá",
  "gachantiva": "Gachantivá",
  "gacheta": "Gachetá",
  "galan": "Galán",
  "galapa": "Galapa",
  "galeras": "Galeras",
  "gama": "Gama",
  "gamarra": "Gamarra",
  "gambita": "Gámbita",
  "gameza": "Gámeza",
  "garagoa": "Garagoa",
  "genova": "Génova",
  "gigante": "Gigante",
  "ginebra": "Ginebra",
  "giraldo": "Giraldo",
  "gomez plata": "Gómez Plata",
  "gonzalez": "González",
  "gramalote": "Gramalote",
  "guaca": "Guaca",
  "guacamayas": "Guacamayas",
  "guacari": "Guacarí",
  "guachene": "Guachené",
  "guacheta": "Guachetá",
  "guachucal": "Guachucal",
  "guadalupe": "Guadalupe",
  "guaitarilla": "Guaitarilla",
  "gualmatan": "Gualmatán",
  "guamal": "Guamal",
  "guamo": "Guamo",
  "guapi": "Guapí",
  "guapota": "Guapotá",
  "guaranda": "Guaranda",
  "guarne": "Guarne",
  "guasca": "Guasca",
  "guatape": "Guatapé",
  "guataqui": "Guataquí",
  "guatavita": "Guatavita",
  "guateque": "Guateque",
  "guatica": "Guática",
  "guavata": "Guavatá",
  "guayabal de siquima": "Guayabal de Síquima",
  "guayabetal": "Guayabetal",
  "guayata": "Guayatá",
  "guepsa": "Güepsa",
  "guican": "Güicán",
  "gutierrez": "Gutiérrez",
  "hacari": "Hacarí",
  "hatillo de loba": "Hatillo de Loba",
  "hato": "Hato",
  "hato corozal": "Hato Corozal",
  "hatonuevo": "Hatonuevo",
  "heliconia": "Heliconia",
  "herran": "Herrán",
  "herveo": "Herveo",
  "hispania": "Hispania",
  "hobo": "Hobo",
  "icononzo": "Icononzo",
  "iles": "Iles",
  "imues": "Imués",
  "inza": "Inzá",
  "iquira": "Íquira",
  "isnos": "Isnos",
  "istmina": "Istmina",
  "ituango": "Ituango",
  "iza": "Iza",
  "jambalo": "Jambaló",
  "jardin": "Jardín",
  "jenesano": "Jenesano",
  "jerico": "Jericó",
  "jerusalen": "Jerusalén",
  "jesus maria": "Jesús María",
  "jordan": "Jordán",
  "juan de acosta": "Juan de Acosta",
  "junin": "Junín",
  "jurado": "Juradó",
  "la apartada": "La Apartada",
  "la argentina": "La Argentina",
  "la belleza": "La Belleza",
  "la capilla": "La Capilla",
  "la ceja": "La Ceja",
  "la celia": "La Celia",
  "la cruz": "La Cruz",
  "la cumbre": "La Cumbre",
  "la esperanza": "La Esperanza",
  "la estrella": "La Estrella",
  "la florida": "La Florida",
  "la gloria": "La Gloria",
  "la jagua de ibirico": "La Jagua de Ibirico",
  "la jagua del pilar": "La Jagua del Pilar",
  "la llanada": "La Llanada",
  "la macarena": "La Macarena",
  "la merced": "La Merced",
  "la montanita": "La Montañita",
  "la palma": "La Palma",
  "la paz": "La Paz",
  "la pena": "La Peña",
  "la pintada": "La Pintada",
  "la playa de belen": "La Playa de Belén",
  "la primavera": "La Primavera",
  "la salina": "La Salina",
  "la sierra": "La Sierra",
  "la tola": "La Tola",
  "la uribe": "La Uribe",
  "la uvita": "La Uvita",
  "la vega": "La Vega",
  "la victoria": "La Victoria",
  "la virginia": "La Virginia",
  "labateca": "Labateca",
  "labranzagrande": "Labranzagrande",
  "landazuri": "Landázuri",
  "lebrija": "Lebrija",
  "leiva": "Leiva",
  "lejanias": "Lejanías",
  "lenguazaque": "Lenguazaque",
  "lerida": "Lérida",
  "liborina": "Liborina",
  "linares": "Linares",
  "litoral de san juan": "Litoral de San Juan",
  "lloro": "Lloró",
  "lopez de micay": "López de Micay",
  "los andes": "Los Andes",
  "los cordobas": "Los Córdobas",
  "los palmitos": "Los Palmitos",
  "los santos": "Los Santos",
  "lourdes": "Lourdes",
  "luruaco": "Luruaco",
  "macanal": "Macanal",
  "macaravita": "Macaravita",
  "maceo": "Maceo",
  "macheta": "Machetá",
  "magui payan": "Magüí Payán",
  "mahates": "Mahates",
  "majagual": "Majagual",
  "mallama": "Mallama",
  "manati": "Manatí",
  "manaure": "Manaure",
  "manaure balcon del cesar": "Manaure Balcón del Cesar",
  "mani": "Maní",
  "manta": "Manta",
  "manzanares": "Manzanares",
  "mapiripan": "Mapiripán",
  "margarita": "Margarita",
  "maria la baja": "María la Baja",
  "marinilla": "Marinilla",
  "maripi": "Maripí",
  "mariquita": "Mariquita",
  "marmato": "Marmato",
  "marquetalia": "Marquetalia",
  "marsella": "Marsella",
  "marulanda": "Marulanda",
  "matanza": "Matanza",
  "medina": "Medina",
  "medio atrato": "Medio Atrato",
  "medio baudo": "Medio Baudó",
  "medio san juan": "Medio San Juan",
  "mercaderes": "Mercaderes",
  "mesetas": "Mesetas",
  "milan": "Milán",
  "miraflores": "Miraflores",
  "miranda": "Miranda",
  "mistrato": "Mistrató",
  "mogotes": "Mogotes",
  "molagavita": "Molagavita",
  "momil": "Momil",
  "mompos": "Mompós",
  "mongua": "Mongua",
  "mongui": "Monguí",
  "monitos": "Moñitos",
  "montebello": "Montebello",
  "montecristo": "Montecristo",
  "monterrey": "Monterrey",
  "morales": "Morales",
  "morelia": "Morelia",
  "morroa": "Morroa",
  "motavita": "Motavita",
  "murillo": "Murillo",
  "murindo": "Murindó",
  "mutata": "Mutatá",
  "mutiscua": "Mutiscua",
  "muzo": "Muzo",
  "narino": "Nariño",
  "nataga": "Nátaga",
  "natagaima": "Natagaima",
  "nechi": "Nechí",
  "necocli": "Necoclí",
  "neira": "Neira",
  "nemocon": "Nemocón",
  "nilo": "Nilo",
  "nimaima": "Nimaima",
  "nobsa": "Nobsa",
  "nocaima": "Nocaima",
  "norcasia": "Norcasia",
  "norosi": "Norosí",
  "novita": "Nóvita",
  "nueva granada": "Nueva Granada",
  "nuevo colon": "Nuevo Colón",
  "nunchia": "Nunchía",
  "nuqui": "Nuquí",
  "obando": "Obando",
  "ocamonte": "Ocamonte",
  "oiba": "Oiba",
  "oicata": "Oicatá",
  "olaya": "Olaya",
  "olaya herrera": "Olaya Herrera",
  "onzaga": "Onzaga",
  "oporapa": "Oporapa",
  "orito": "Orito",
  "orocue": "Orocué",
  "ortega": "Ortega",
  "ospina": "Ospina",
  "otanche": "Otanche",
  "ovejas": "Ovejas",
  "pachavita": "Pachavita",
  "pacho": "Pacho",
  "pacora": "Pácora",
  "padilla": "Padilla",
  "paez": "Páez",
  "paicol": "Paicol",
  "pailitas": "Pailitas",
  "paime": "Paime",
  "paipa": "Paipa",
  "pajarito": "Pajarito",
  "palermo": "Palermo",
  "palestina": "Palestina",
  "palmar": "Palmar",
  "palmar de varela": "Palmar de Varela",
  "palmas del socorro": "Palmas del Socorro",
  "palocabildo": "Palocabildo",
  "pamplonita": "Pamplonita",
  "pandi": "Pandi",
  "panqueba": "Panqueba",
  "paramo": "Páramo",
  "paratebueno": "Paratebueno",
  "pasca": "Pasca",
  "patia": "Patía",
  "pauna": "Pauna",
  "paya": "Paya",
  "paz de ariporo": "Paz de Ariporo",
  "paz del rio": "Paz del Río",
  "pedraza": "Pedraza",
  "pelaya": "Pelaya",
  "pensilvania": "Pensilvania",
  "peque": "Peque",
  "pesca": "Pesca",
  "piamonte": "Piamonte",
  "piedras": "Piedras",
  "piendamo": "Piendamó",
  "pijao": "Pijao",
  "pijino del carmen": "Pijiño del Carmen",
  "pinchote": "Pinchote",
  "pinillos": "Pinillos",
  "piojo": "Piojó",
  "pisba": "Pisba",
  "pivijay": "Pivijay",
  "planadas": "Planadas",
  "policarpa": "Policarpa",
  "polonuevo": "Polonuevo",
  "ponedera": "Ponedera",
  "pore": "Pore",
  "potosi": "Potosí",
  "pradera": "Pradera",
  "prado": "Prado",
  "providencia": "Providencia",
  "providencia y santa catalina islas": "Providencia y Santa Catalina Islas",
  "pueblo bello": "Pueblo Bello",
  "pueblo nuevo": "Pueblo Nuevo",
  "pueblo rico": "Pueblo Rico",
  "pueblo viejo": "Pueblo Viejo",
  "pueblorrico": "Pueblorrico",
  "puente nacional": "Puente Nacional",
  "puerres": "Puerres",
  "puerto berrio": "Puerto Berrío",
  "puerto boyaca": "Puerto Boyacá",
  "puerto caicedo": "Puerto Caicedo",
  "puerto colombia": "Puerto Colombia",
  "puerto concordia": "Puerto Concordia",
  "puerto escondido": "Puerto Escondido",
  "puerto gaitan": "Puerto Gaitán",
  "puerto guzman": "Puerto Guzmán",
  "puerto leguizamo": "Puerto Leguízamo",
  "puerto libertador": "Puerto Libertador",
  "puerto lleras": "Puerto Lleras",
  "puerto nare": "Puerto Nare",
  "puerto narino": "Puerto Nariño",
  "puerto parra": "Puerto Parra",
  "puerto rico": "Puerto Rico",
  "puerto rondon": "Puerto Rondón",
  "puerto salgar": "Puerto Salgar",
  "puerto santander": "Puerto Santander",
  "puerto tejada": "Puerto Tejada",
  "puerto triunfo": "Puerto Triunfo",
  "puerto wilches": "Puerto Wilches",
  "puli": "Pulí",
  "pupiales": "Pupiales",
  "purace": "Puracé",
  "purificacion": "Purificación",
  "purisima": "Purísima",
  "quebradanegra": "Quebradanegra",
  "quetame": "Quetame",
  "quinchia": "Quinchía",
  "quipama": "Quípama",
  "quipile": "Quipile",
  "ragonvalia": "Ragonvalia",
  "ramiriqui": "Ramiriquí",
  "raquira": "Ráquira",
  "recetor": "Recetor",
  "regidor": "Regidor",
  "remedios": "Remedios",
  "remolino": "Remolino",
  "repelon": "Repelón",
  "restrepo": "Restrepo",
  "ricaurte": "Ricaurte",
  "rio de oro": "Río de Oro",
  "rio iro": "Río Iró",
  "rio quito": "Río Quito",
  "rio viejo": "Río Viejo",
  "rioblanco": "Rioblanco",
  "riofrio": "Riofrío",
  "risaralda": "Risaralda",
  "rivera": "Rivera",
  "roberto payan": "Roberto Payán",
  "roncesvalles": "Roncesvalles",
  "rondon": "Rondón",
  "rosas": "Rosas",
  "rovira": "Rovira",
  "sabana de torres": "Sabana de Torres",
  "sabanagrande": "Sabanagrande",
  "sabanalarga": "Sabanalarga",
  "sabanas de san angel": "Sabanas de San Ángel",
  "saboya": "Saboyá",
  "sacama": "Sácama",
  "sachica": "Sáchica",
  "saladoblanco": "Saladoblanco",
  "salamina": "Salamina",
  "salazar de las palmas": "Salazar de las Palmas",
  "saldana": "Saldaña",
  "salento": "Salento",
  "salgar": "Salgar",
  "samaca": "Samacá",
  "samana": "Samaná",
  "samaniego": "Samaniego",
  "sampues": "Sampués",
  "san agustin": "San Agustín",
  "san alberto": "San Alberto",
  "san andres de cuerquia": "San Andrés de Cuerquia",
  "san andres de sotavento": "San Andrés de Sotavento",
  "san antero": "San Antero",
  "san antonio": "San Antonio",
  "san antonio de palmito": "San Antonio de Palmito",
  "san antonio del tequendama": "San Antonio del Tequendama",
  "san benito": "San Benito",
  "san benito abad": "San Benito Abad",
  "san bernardo": "San Bernardo",
  "san bernardo del viento": "San Bernardo del Viento",
  "san calixto": "San Calixto",
  "san carlos": "San Carlos",
  "san carlos de guaroa": "San Carlos de Guaroa",
  "san cayetano": "San Cayetano",
  "san cristobal": "San Cristóbal",
  "san diego": "San Diego",
  "san eduardo": "San Eduardo",
  "san estanislao": "San Estanislao",
  "san fernando": "San Fernando",
  "san francisco": "San Francisco",
  "san jacinto": "San Jacinto",
  "san jacinto del cauca": "San Jacinto del Cauca",
  "san jeronimo": "San Jerónimo",
  "san joaquin": "San Joaquín",
  "san jose": "San José",
  "san jose de alban": "San José de Albán",
  "san jose de la montana": "San José de la Montaña",
  "san jose de miranda": "San José de Miranda",
  "san jose de pare": "San José de Pare",
  "san jose de ure": "San José de Uré",
  "san jose del fragua": "San José del Fragua",
  "san jose del palmar": "San José del Palmar",
  "san juan de arama": "San Juan de Arama",
  "san juan de betulia": "San Juan de Betulia",
  "san juan de rioseco": "San Juan de Rioseco",
  "san juan de uraba": "San Juan de Urabá",
  "san juan nepomuceno": "San Juan Nepomuceno",
  "san juanito": "San Juanito",
  "san lorenzo": "San Lorenzo",
  "san luis": "San Luis",
  "san luis de gaceno": "San Luis de Gaceno",
  "san luis de palenque": "San Luis de Palenque",
  "san marcos": "San Marcos",
  "san martin": "San Martín",
  "san martin de loba": "San Martín de Loba",
  "san mateo": "San Mateo",
  "san miguel": "San Miguel",
  "san miguel de sema": "San Miguel de Sema",
  "san onofre": "San Onofre",
  "san pablo": "San Pablo",
  "san pablo de borbur": "San Pablo de Borbur",
  "san pedro": "San Pedro",
  "san pedro de cartago": "San Pedro de Cartago",
  "san pedro de los milagros": "San Pedro de los Milagros",
  "san pedro de uraba": "San Pedro de Urabá",
  "san pelayo": "San Pelayo",
  "san rafael": "San Rafael",
  "san roque": "San Roque",
  "san sebastian": "San Sebastián",
  "san sebastian de buenavista": "San Sebastián de Buenavista",
  "san vicente": "San Vicente",
  "san vicente de chucuri": "San Vicente de Chucurí",
  "san vicente del caguan": "San Vicente del Caguán",
  "san zenon": "San Zenón",
  "sandona": "Sandoná",
  "santa ana": "Santa Ana",
  "santa barbara": "Santa Bárbara",
  "santa barbara de pinto": "Santa Bárbara de Pinto",
  "santa catalina": "Santa Catalina",
  "santa fe de antioquia": "Santa Fe de Antioquia",
  "santa helena del opon": "Santa Helena del Opón",
  "santa isabel": "Santa Isabel",
  "santa lucia": "Santa Lucía",
  "santa maria": "Santa María",
  "santa rosa": "Santa Rosa",
  "santa rosa de osos": "Santa Rosa de Osos",
  "santa rosa de viterbo": "Santa Rosa de Viterbo",
  "santa rosa del sur": "Santa Rosa del Sur",
  "santa rosalia": "Santa Rosalía",
  "santa sofia": "Santa Sofía",
  "santacruz": "Santacruz",
  "santana": "Santana",
  "santiago": "Santiago",
  "santo domingo": "Santo Domingo",
  "santo domingo de silos": "Santo Domingo de Silos",
  "santo tomas": "Santo Tomás",
  "santuario": "Santuario",
  "sapuyes": "Sapuyes",
  "sardinata": "Sardinata",
  "sasaima": "Sasaima",
  "sativanorte": "Sativanorte",
  "sativasur": "Sativasur",
  "segovia": "Segovia",
  "sesquile": "Sesquilé",
  "siachoque": "Siachoque",
  "sibate": "Sibaté",
  "silvania": "Silvania",
  "silvia": "Silvia",
  "simacota": "Simacota",
  "simijaca": "Simijaca",
  "simiti": "Simití",
  "since": "Sincé",
  "sipi": "Sipí",
  "sitionuevo": "Sitionuevo",
  "soata": "Soatá",
  "socha": "Socha",
  "socota": "Socotá",
  "solano": "Solano",
  "solita": "Solita",
  "somondoco": "Somondoco",
  "sonson": "Sonsón",
  "sopetran": "Sopetrán",
  "soplaviento": "Soplaviento",
  "sora": "Sora",
  "soraca": "Soracá",
  "sotaquira": "Sotaquirá",
  "sotara": "Sotará",
  "suaita": "Suaita",
  "suan": "Suán",
  "suarez": "Suárez",
  "suaza": "Suaza",
  "sucre": "Sucre",
  "suesca": "Suesca",
  "supata": "Supatá",
  "supia": "Supía",
  "surata": "Suratá",
  "susa": "Susa",
  "susacon": "Susacón",
  "sutamarchan": "Sutamarchán",
  "sutatausa": "Sutatausa",
  "sutatenza": "Sutatenza",
  "tabio": "Tabio",
  "tado": "Tadó",
  "talaigua nuevo": "Talaigua Nuevo",
  "tamalameque": "Tamalameque",
  "tamara": "Támara",
  "tamesis": "Támesis",
  "taminango": "Taminango",
  "tangua": "Tangua",
  "taraira": "Taraira",
  "taraza": "Tarazá",
  "tarqui": "Tarqui",
  "tarso": "Tarso",
  "tasco": "Tasco",
  "tauramena": "Tauramena",
  "tausa": "Tausa",
  "tello": "Tello",
  "tena": "Tena",
  "tenerife": "Tenerife",
  "tenjo": "Tenjo",
  "tenza": "Tenza",
  "teorama": "Teorama",
  "teruel": "Teruel",
  "tesalia": "Tesalia",
  "tibacuy": "Tibacuy",
  "tibana": "Tibaná",
  "tibasosa": "Tibasosa",
  "tibirita": "Tibirita",
  "tibu": "Tibú",
  "tierralta": "Tierralta",
  "timana": "Timaná",
  "timbio": "Timbío",
  "timbiqui": "Timbiquí",
  "tinjaca": "Tinjacá",
  "tipacoque": "Tipacoque",
  "tiquisio": "Tiquisio",
  "titiribi": "Titiribí",
  "toca": "Toca",
  "tocaima": "Tocaima",
  "togui": "Togüí",
  "toledo": "Toledo",
  "tolu": "Tolú",
  "tolu viejo": "Tolú Viejo",
  "tona": "Tona",
  "topaga": "Tópaga",
  "topaipi": "Topaipí",
  "toribio": "Toribío",
  "toro": "Toro",
  "tota": "Tota",
  "totoro": "Totoró",
  "trinidad": "Trinidad",
  "trujillo": "Trujillo",
  "tubara": "Tubará",
  "tuchin": "Tuchín",
  "tunungua": "Tununguá",
  "turbana": "Turbaná",
  "turmeque": "Turmeque",
  "tuta": "Tuta",
  "tutaza": "Tutazá",
  "ubala": "Ubalá",
  "ubaque": "Ubaque",
  "ulloa": "Ulloa",
  "umbita": "Úmbita",
  "une": "Une",
  "unguia": "Unguía",
  "union panamericana": "Unión Panamericana",
  "uramita": "Uramita",
  "urrao": "Urrao",
  "urumita": "Urumita",
  "usiacuri": "Usiacurí",
  "utica": "Útica",
  "valdivia": "Valdivia",
  "valencia": "Valencia",
  "valle de san jose": "Valle de San José",
  "valle de san juan": "Valle de San Juan",
  "valle del guamuez": "Valle del Guamuez",
  "valparaiso": "Valparaíso",
  "vegachi": "Vegachí",
  "velez": "Vélez",
  "venadillo": "Venadillo",
  "venecia": "Venecia",
  "ventaquemada": "Ventaquemada",
  "vergara": "Vergara",
  "versalles": "Versalles",
  "vetas": "Vetas",
  "viani": "Viani",
  "victoria": "Victoria",
  "vigia del fuerte": "Vigía del Fuerte",
  "vijes": "Vijes",
  "villa caro": "Villa Caro",
  "villa rica": "Villa Rica",
  "villagarzon": "Villagarzón",
  "villagomez": "Villagómez",
  "villahermosa": "Villahermosa",
  "villapinzon": "Villapinzón",
  "villarrica": "Villarrica",
  "villavieja": "Villavieja",
  "villeta": "Villeta",
  "viota": "Viotá",
  "viracacha": "Viracachá",
  "vista hermosa": "Vista Hermosa",
  "viterbo": "Viterbo",
  "yacopi": "Yacopí",
  "yacuanquer": "Yacuanquer",
  "yaguara": "Yaguará",
  "yali": "Yalí",
  "yarumal": "Yarumal",
  "yolombo": "Yolombó",
  "yondo": "Yondó",
  "yotoco": "Yotoco",
  "zambrano": "Zambrano",
  "zapatoca": "Zapatoca",
  "zapayan": "Zapayán",
  "zaragoza": "Zaragoza",
  "zetaquira": "Zetaquira",
  "zipacon": "Zipacón",
  "zona bananera": "Zona Bananera",
};

/**
 * Departamentos y sufijos que NO deben aparecer en `lugarexpedicion`.
 * Se comparan normalizados.
 */
export const DEPARTMENTS = new Set<string>([
  'amazonas',
  'antioquia',
  'arauca',
  'atlantico',
  'bolivar',
  'boyaca',
  'caldas',
  'caqueta',
  'casanare',
  'cauca',
  'cesar',
  'choco',
  'cordoba',
  'cundinamarca',
  'guainia',
  'guaviare',
  'huila',
  'la guajira',
  'guajira',
  'magdalena',
  'meta',
  'narino',
  'norte de santander',
  'putumayo',
  'quindio',
  'risaralda',
  'san andres y providencia',
  'archipielago de san andres',
  'santander',
  'sucre',
  'tolima',
  'valle del cauca',
  'valle',
  'vaupes',
  'vichada',
  'distrito capital',
  'colombia',
]);

/**
 * Municipios que comparten nombre con un departamento. En estos casos el
 * texto es válido como ciudad y no debe reportarse como "departamento".
 */
export const CITY_DEPARTMENT_HOMONYMS = new Set<string>([
  'arauca',
  'caldas',
  'cordoba',
  'santander',
  'sucre',
  'bolivar',
  'magdalena',
  'guajira',
]);
